coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null